### ISSUE TITLE
"Quantum" random?

### ISSUE THREAD

**Issue by giuliohome** [autonomio/talos#113]
How do you implement a quantum random generator? Being quantum is a physical characteristic of the process and it is hard to achieve in practice but anyway it makes sense only when speaking about physics and typically at either experimental or fundamental level.
You can not achieve a true quantum outcome only by means of a classical software code.
Is it really _quantum_ what you _call_ **quantum** ? Or what's it indeed?  

what about this line of code in your [reducer](https://github.com/autonomio/talos/blob/e97f4b782068993afb77ace350f68bc008c20ccc/talos/reducers/sample_reducer.py#L52): how is it supposed to be implemented?  

Notice that you write in the readme:

> The currently implemented methods are:

Quantum randomness (vacuum based)

**Comment by mikkokotila** [comment]
That's right, we're using an API from a lab that produces the quantum randoms mechanically. Here is the description:

> The random numbers are generated in real-time in our lab by measuring the quantum fluctuations of the vacuum. The vacuum is described very differently in the quantum mechanical context than in the classical context. Traditionally, a vacuum is considered as a space that is empty of matter or photons. Quantum mechanically, however, that same space resembles a sea of virtual particles appearing and disappearing all the time. This result is due to the fact that the vacuum still possesses a zero-point energy. Consequently, the electromagnetic field of the vacuum exhibits random fluctuations in phase and amplitude at all frequencies. By carefully measuring these fluctuations, we are able to generate ultra-high bandwidth random numbers.

You could read more [from the paper](https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.3.054004).

Then this of course leads to the bigger question about using computer to produce random numbers. We are conducting an experiment that might take a year or so, where we throw high precision laser cut dice some tens of millions of times (with a high-precision mechanical device), and then compare the results with the different methods of randomness (including the quantum and ambient sound which are not computer generated strictly speaking) to identify which is the "most" random so-to-speak. Of course, here we come to the main questions i.e. which random yields an acceptable result from a hyperparameter search in the least amount time (compute resources being the same). That is another study we are working on. Some studies argue that it's quasi-random sequences, which is why we've implemented some of those. It really comes down to that one question, being that the observation effect shows how the very act of taking a random sample contradicts randomness. The other point being here, that as I had mentioned, some indications are there in literature that suggest that low-discrepancy options (like Sobol) might be more effective for the hyperparameter optimization problem. 

As it stands, random functions are widely used in deep learning (not just to reduce possible permutations vs. grid search), while only little research is focused on answering fundamental questions about its effect on everything we are doing. 

In the longer term, this will have its own life [here](https://github.com/autonomio/changes) under the name Chances.

**Comment by giuliohome** [comment]
Thank you for the prompt response and the longer explanation in the links!
