### ISSUE TITLE
Working with Predict without saving a file

### ISSUE THREAD

**Issue by rahutchinson** [autonomio/talos#126]
Hello,

Using Talos every day for the past week or so. Working with lots of models which I run `predict()` on for validation. I am having an issue trying to find a way to predict without having to create a file. I've got a large core box running 24/7 creating lots of models. I would rather not create so many directories and zips for the models.   I forked and made a quick change to the `deploy()` command by pulling all the saving into another function and adding a flag to pass to init, also having it return an activate model when given the model specs just like restore does. 

I am wondering if I missed something in the documentation or in the code that will allow me to use the prediction on a keras model object without send the scan obejct to a file via csv or with deploy. 

 - if there **is** a way point it out to me and I will update the documentation and put in a pull request
 - if there **isn't** a way and this is something that is applicable to contribute I will happily make my _first_ contribution

Thanks!

**Comment by rahutchinson** [comment]
Looks like the answer to my question is in utils.best_model with `activate_model()` ? 

If this is correct let me know and I can put it in the documentation.

Another solution I was thinking about is a little bit larger refactor with the scan object. Where `scan_object.saved_models` holds the keras models themselves instead being changed to json object. 

again either way let me know an I will be happy to do it.

**Comment by rahutchinson** [comment]
Nevermind.

**Comment by mikkokotila** [comment]
Hey, sorry for the delay.

There are several ways to do this. Evaluate() would be one, and then other as you had pointed out would be using best model. As a background for the approach we have for saving models, it has to do with the need to overcome the ambiguities that come with 

For documentation, the issue is that it's not enough to make PR and merge, but the whole thing needs to be still built and upon building everything changes. I have to figure out a clear guideline for how to allow anyone to improve the documentation. I'm using lord/slate for the docs. It will be create if you want to update it, and I guess we'd as a byproduct then figure out the best way to manage it (and document it as a reference for those who in the future want to do the same).

**Comment by rahutchinson** [comment]
Thanks and I found my solution really in the model_from_json that keras has. Got a bit confusing since Talos is a sudo-wrapper for keras and keras is a wrapper for tensorflow.

Thanks for the help.

**Comment by mikkokotila** [comment]
This came up in #133 so posting it here as well. The one-liner to make predictions from the Scan() object is:

`activate_model(scan_object, best_model(scan_object, 'val_acc', False)).predict(X)`

Also note that the reason why the models are saved the way they are, is to avoid an issue in the Keras/TF way of handling the tf graph which basically breaks after the current iteration is done. So the safest way to handle many models in the way we need to do, seems to be the current implementation. In the corresponding issues in Keras repo there are at least 10 different version to how to overcome the issue, and nobody seems to really able to convincingly explain why what they do works. So I decided it's better to do things in a way where maybe it's not the neatest, but we can be 100% sure that what we see is what we get.

**Comment by rahutchinson** [comment]
Great. Thanks for the explanation. The more I get integrated the more I hope I can provide value to the project!

Thanks again.
