### ISSUE TITLE
ImportError: cannot import name 'early_stopper'

### ISSUE THREAD

**Issue by Neabfi** [autonomio/talos#13]
I'm trying to follow the notebook but I have the following issue: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-54-45124b1b47d4> in <module>()
      7 from keras.layers import Conv1D, GlobalMaxPooling1D, Dense, Softmax
      8 import hyperio as hy
----> 9 from hyperio import early_stopper

ImportError: cannot import name 'early_stopper'
```

**Comment by mikkokotila** [comment]
What Python version are you on?

    python -V

**Comment by Neabfi** [comment]
Python 3.6.5

**Comment by mikkokotila** [comment]
Ah ok I see what's going on. The Notebook is raising the error because it's still referring to the old package name which is 'hyperio'. To use that notebook you want to:

`pip install talos
`
And then replace all the hyperio/hy references with talos. 

Thanks for raising this, I will clean up the Notebook as well and replace with a new one.

**Comment by mikkokotila** [comment]
Created #14 regarding the Iris Notebook update.
