### ISSUE TITLE
How is shapes:  ['rhombus'] supposed to work?

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#202]
I was using the shapes parameter to hidden_leyers
To my supprise when the rhombus model got selected with 3 hidden layers and first_neuron 20 I got this

1
20
1

for layer neurons. Is that right? What is it supposed to be?

**Comment by mikkokotila** [comment]
Related with #10. Fixing this is long due. I think there are many similar issues that manifest in surprising ways. Rhombus is tricky, because the only way to achieve the precise shape is by assuming input to be equal to output (in your case 1) and have the max value for neurons (your case 20) as the middle. It's logical, but not useful. The automated shape generation is surprisingly tricky I found. 

Nevertheless, it's the oldest part of the code and dates back to an earlier (and experimental) Autonomio project. Redoing it from scratch is long overdue.

**Comment by JohanMollevik** [comment]
I can add that hexagon, diamond and triangle also does not respect first_neuron
What I would have expected would have been more like

20
40
20

rather than

1
20
1

so that first and last neuron is respected and the shape being maintained by scaling up from there, I suppose other shapes like hourglas could be added to support shapes like

20
1
20

or however narrow one wants it to go

**Comment by mikkokotila** [comment]
This will be done today. I spent  some time yesterday on this and will be able to push to daily-dev shortly I think. Basically we have to let go of the old shapes and have a repeatable and logical way for handling shapes.

**Comment by JohanMollevik** [comment]
Sounds good, better a consistent set that works rather than stubbornly maintaining backwards compatability

**Comment by mikkokotila** [comment]
This is resolved in v.0.4.9 now available in daily-dev. Closing here.

**Comment by JohanMollevik** [comment]
Great to get this resolved
