### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by pankap** [autonomio/talos#216]
Dear contributors,

It seems that we are in a bizarre situation that we are both using the same name for our projects. I couldn't find any other contact info, that is why I am posting here.

I have started TALOS (Tensor Abstraction Layer ObjectS) in 2017  https://github.com/pankap/talos but since then my repository was not so active. I have presented a tutorial on TALOS at AUTH university and also mentioned my framework in a paper published at the ICIP2018 conference.

I am looking for the best solution so that both our works would not be confused. I have created a Keras like framework and as I understand yours is an add-on for hyperparameter search. I would kindly ask if some distinction can be made in your naming, so it would not be confusing with my acronym.

Thank you very much in advance and if you prefer we can continue the discussion in private.

**Comment by mikkokotila** [comment]
Thank you for kindly reaching out. I understand your concern and indeed there is a case for agreeing mutually to something. Thank you also for sharing about your package.

At the moment there are [346](https://github.com/search?q=talos) repositories that come up with the keyword Talos. [Many](https://www.google.com/search?q=talos&oq=talos&aqs=chrome..69i57j69i60l4j0.3456j1j4&sourceid=chrome&ie=UTF-8) Talos are also coming up in Google search. Because of the meaning of the word, I assume many have to do with machine intelligence, and many more will come in the future. That is an unfortunate downside of the ease in which new projects can be initiated these days.

I think the problem would lie in the case where two packages had become popular, and were doing a similar thing. This would indeed confuse users, and make things like [asking questions on stackoverflow](https://stackoverflow.com/search?q=talos) difficult.

One important distinction here is that Talos has many active users across disciplines of scientific research and we know as a fact that tens of thousands of people have come across it. Every week several thousand people come to the repo. It would therefore be difficult for me to agree to do anything that would potentially become a source of confusion for all those people.
