### ISSUE TITLE
Ability to filter valid premutations

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#223]
It would be usefull to be able to filter the generated parameters to support removing invalid combinations

Suppose that we have 2 parameters
params = {
 'p1': (1,7,7),
 'p2': (1,7,7)
}

and some constraint in the model makes the model fail if the sum is larger than 10 (I have an issue like this with convolutional layers)

If we could pass a filter function to Scan to remove them during the downsampling stage we could simplify the client code.

Is this something you could include in the codebase, I would be willing to work on a patch for this if you think it fits with where you want to take talos.

**Comment by mikkokotila** [comment]
All kinds of capabilities that allow removing noise or automating the inference of experiment attributes are most meaningful. Particularly the latter is important...it will keep paying dividends as we keep automating/abstracting.  

How do you foresee it working? Would it be something like lr_normalizer or hidden_layers i.e. a stand-alone utility, or something more built-in? Generally the preference is to have anything with "magics"  (e.g. inference of attributes >> making changes automatically) as utils. 

Related with that, in the v.0.5.0 namespace things like this will be tidy/accessible under `ta.utils` from where it can then be used directly.

**Comment by JohanMollevik** [comment]
The way I envissioned it was a parameter to scan called premutation_filter or something like that. The parameter would expect a function that takes a param object in the same format as the model function and returns True or False depending on whether we want to keep it or not. How does that sounds?

**Comment by mikkokotila** [comment]
I spent some time testing this yesterday, and cleaned it up a little https://github.com/autonomio/talos/commit/9787ff150e185ff5a51a25c69978d2c50621ce79 as well as moving it to its own function under parameters, but I think it belongs to reducers so it might end up there. Because it basically serves the purpose of reducing the sample. This leads to an important point. 

It seems to me that right now what happens is that this over-rides grid downsampling. This means that if both `permutation_filter` and `grid_downsample`are applied, `permutation_filter` makes whatever `grid_dowsample` have done null. 

### Useful background information

Basically the Talos use design is as follows: 

1) setup the experiment >> creates the experiment
2) decide a random method to decrease grid size >> creates the permutation grid and index
3) apply reducers  to further decrease the grid size  >> edits the index

The way a reducer works is that it goes to the current results, and identifies what is contributing performance / lack of performance and outputs a parameter value, parameter values, or combinations of parameter values. 

As I can see, permutation_filter is on one hand a means to explicitly state reduction criteria and apply it right at the beginning of the experiment, and on the other it provides a meaningful interface to accept outputs from all reducers, find the index numbers from the current grid, and block those index numbers from the current index. 

Once we figure out how to fit permutation_filter to this bigger picture, the "over-riding" issue mentioned above is also automatically resolved. The key point is to retain the design flow: 

- create experiment (Scan)
- create grid and index (grid_downsample)
- edit the index to block values (everything else)

@JohanMollevik What do you think?

**Comment by JohanMollevik** [comment]
First if it voids the result of the downsample then that is sa bug, the design I aimed at was to return exactly as many results that the downsample would have returned.

Right, I was viewing it as a downsampling step where I change the shape of the premutation hypercube to only consider some parts of it. The reason I did it like that is to respect round_limit and not run fewer iterations than specified, suppose that I feel I need 200 ierations to get reliable statistics I would like it to run exactly 200 times and not less. If I on the other hand did a grid downsample then the current reducer design makes sense.

Are my way of looking at it like a downsampling step workable or do you want it to change to be more of a reducer?

**Comment by mikkokotila** [comment]
@JohanMollevik  Thanks for clarifying, that helps me to think about the taxonomy/levels more clearly. I will open a new thread as the topic is broader than this feature...let's see where we end up :)

**Comment by JohanMollevik** [comment]
Sounds good

**Comment by mikkokotila** [comment]
This appears to be handled so closing here. Also, there is now a new reducer `local_strategy` which allows you to make changes to the params dictionary while the experiment is running. This is particularly powerful together with `ExperimentLogCallback` which gives you the epoch-by-epoch training data during the experiment on local. 

Closing here.
