### ISSUE TITLE
Talos conventions

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#264]
Slightly related with #256. 

For the past few days I've been working on a major overhaul of the codebase. Over the past few months I've noticed three things:

- there are parts of the code that are rather cryptic
- some things (like inferring metric names) are done many times
- the mainline code is all over the place (goes from here to there in a way that is difficult to follow) 

I've thought, as part of this process, some basic conventions for going forward. 

- /commands contains one file per command (end-user command)
- /scan contains everything related with Scan
- /reducers contains all kinds of limits and reducers 
- if the file name is *_run.py it represents the main procedural code of that aspect
- if the file name is * _prepare.py or *_prepare.py it is called only from corresponding *_run.py
- in all other cases, the docstring has to start with "Called from path/function.py" 
- imports outside of talos are made inside each function below doctstring
- imports outside of talos must contain a two letter prefix e.g. `import numpy as np`
- import outside of talos may alternatively be in the form `import numpy`
- NOTE: it's absolutely prohibited to perform absolute imports e.g. `from numpy import array`
- imports from inside talos are made immediately before the corresponding line of code
- import from inside talos are always absolute imports (to disclose the full path to the originating code)
- a reducer (e.g. correlation) is a single self-contained function in its own file
- a reducer accepts self from Scan() only and returns `value` and `label` only where label is the parameter label and value is the parameter value

...more to come. Before releasing this overhaul, I will write up a wiki entry with comprehensive information conventions / standards etc.

**Comment by mikkokotila** [comment]
`Scan()` creates a `self` so whenever this is mentioned, it refers specifically to `Scan()`. Otherwise the class originating the function is specifically mentioned. Objects from other classes can be appended as an attribute to `self` and must indicate that it is an object (e.g. `self.param_object`).

More generally regarding names of commands, they must strictly follow the name of the file if only one function is in the file. The name should clearly indicate what it does.

The very basic process flow is:

#### Experiment

- Scan() initiates `scan_run()`
- `scan_run()` initiates other procedures in /scan (e.g. `scan_prepare()`)
- Each round is handled by `scan_round.py`
- Once limits have been met or no more permutations remain in index, `scan_finish.py` handles rest

#### Parameters

- `ParamSpace()` creates and handles parameter space (permutation grid)
-  `ParamSpace()` first handles all the relevant limits
- Based on the limits,  a parameter space and a corresponding index is created
- This is stored to `self.param_object` (e.g. `self.param_object.param_index`)
- The index can be updated anytime through `self.param_object.param_index`
- `self.param_object.remove_is(label, value)` allows removing permutations from the parameter space
- `remove_is_not`, `remove_ge`, `remove_le`, and `remove_lambda` are also provided
- NOTE: `remove_lambda` exceptionally accepts a lambda function instead of label and value
- label is the parameter label, and value is the value of the parameter
- `self.param_object.round_paramaters()` is used for `retrieving` a parameter dictionary with parameters for a single permutation
- `self.param_object.round_paramaters()` returns False when limits have been met or no more permutations remain in the index

#### Reducers
- all reducers are activated through calling `reducers_run.py`
- all new reducers must be added as a reference to `reducers_run.py`
- a reducer (e.g. correlation) is a means to reduce the remaining parameter space 
- a reducer returns False if there is no reason to reduce, and [value, label] otherwise

**Comment by mikkokotila** [comment]
@JohanMollevik what do you think, what kind of things would be important to outline to make Talos as easy to understand from the development/maintenance/extension stand-point.

**Comment by JohanMollevik** [comment]
Hard to tell, these kinds of conventions will probably help but I feel that my single hardest issue with understanding talos code has been the way it saves state into self objects instead of taking more explicit parameters (that it does not modify) and returning the results of an operation in the return value. I am of the opinion that this kind of non mutation code is much easier to understand but on the other hand making a change towards that would be a total change to how it is done now.

The other thing I would warn about is to make to many abstractions, I find it usually easier to read a clear sequential non condintional flow in a single file than a calls to other files that makes me jum back and forth. Don't understand me wrong, modularization and abstraction is good, but only up to a point and I would caution against overdoing it.

I would also emphasise more that when an object is passed from function to function it is nice if it uses the same variable name in all places (when possible), this makes tools like 'git grep' work better to find where some value is comming from.

What would help understanding is what you have done in these posts, documenting the rational behind changes, I would recoment saving the final text of this design in a prominent place in the documentation.

Hope I do not come across as complaining, I think this is a very nice project and it saved me the trouble to write my own incompleate version. So thanks for your great work
