### ISSUE TITLE
Future development: TF 2.0 and tf.keras

### ISSUE THREAD

**Issue by beeb** [autonomio/talos#284]
First, thanks to the author, I love Talos and use it every day for my work. I see that TF 2.0 is starting to emerge as alpha and we can certainly expect a release in the next few months. Is there a plan to adapt Talos to the new `tf.keras` in TF2 in the future?

Thanks!

**Comment by mikkokotila** [comment]
100%. We must do it. Do you already have a handle of the difference between Keras and tf.keras or is it the same?

**Comment by mikkokotila** [comment]
This seems to answer my question: https://www.tensorflow.org/guide/keras

This is really an amazing progression I must say. I think TensorFlow has roughly 5x more users than Keras, so many more people can benefit from Talos :)

**Comment by beeb** [comment]
Amazing news! I don't know if tf.keras differs a lot from normal keras for your purposes. There's a lot of differences under the hood but I think the interface to train the model etc is similar, so my guess is that a lot of your codebase should be compatible. It will require some testing for sure but I hope it's an easy port!

**Comment by mikkokotila** [comment]
To the extent I can see from examples, it might be really just to test that it works rather than having to change / fix something.

**Comment by mikkokotila** [comment]
I've looked into this, and it does seem that from [`v.6.0`](https://github.com/autonomio/talos/tree/params-api-test) onwards, `tf.keras` is supported exactly like `keras` is currently. I think, because of the way Talos works, that one should be able to run TensorFlow codes together with a tf.keras model inside `input_model` for `Scan()`. In facf, one should be able to run any arbitrary codes as long as the model otherwise follows the Talos way (e.g. keras style history object). 

Closing here. Feel free to open a new issue if anything.
