### ISSUE TITLE
Give an option to disable or change path of experiment name.

### ISSUE THREAD

**Issue by fmv1992** [autonomio/talos#312]
First of all thank you for this very useful library!

To the issue:

I see that the result of a `Scan()` operation implies the saving of a model.

Enforcing the creation of files without the explicit command of the user is in general a bad practice. Think of all the software that we use. They may save the results, but if and only if users give explicit directions to do so.

From my understanding I can't even point an absolute path for the Scan to be saved.

**Comment by mikkokotila** [comment]
There is a .csv file stored in your `present working directory` with the results of your experiment. If you declare a name for your experiment, then that will be used, and otherwise the name will be generated based on time when the experiment starts. Having this file updated throughout the run is a meaningful default state for several reasons. For example, if the experiment is interrupted on Saturday afternoon and you come back on Monday, you still have some results to look at. 

I don't see why you would not be able to define a path instead of just name. I suggest using [v.0.6.](https://github.com/autonomio/talos/tree/params-api-test) where logging is handled much better overall. There you will have `experiment_name` argument in `talos.Scan()`. 

Other than that, do you have an example for a case where you absolutely would not want to have a log stored on the local machine as the experiment progress?

**Comment by mikkokotila** [comment]
Closing here, feel free to reopen if you think this is still relevant.
