### ISSUE TITLE
Update the Examples

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#377]
This is related to #376. Example notebooks have to be updated to current versions of Talos.

**Comment by MorissetteThomasV** [comment]
I'm glad this issue is assigned. I found these problems so far :
1) In Comprehensive example, in order to import the datasets, we have to import from this path.
`from talos.templates import datasets`
2) In the talos.Scan parameters, the parameter `dataset_name` as in : 
`h = ta.Scan(x, y, params=p,
            model=iris_model,
            **dataset_name**='iris',
            experiment_no='1',
            grid_downsample=.01)`
needs to be changed to `experiment_name`,
3) `experiment_no ` seems to have been removed
4) `grid_downsample ` is now `fraction_limit`
Thanks

**Comment by mikkokotila** [comment]
@MorissetteThomasV do you want to make a PR for it? That would be great :)
