### ISSUE TITLE
the new released talos 1.0 don't run the example code 

### ISSUE THREAD

**Issue by zzhulm** [autonomio/talos#520]
in my old install with pip install --use-feature=2020-resolver git+https://github.com/autonomio/talos@1.0  working with tensorflow 2.1, the  talso example code is running fine, but when 
I installed the new released talos 1.0 by pip install talos, with the tensorflow 2.31 , the tensorflow runs fine, by when run the same talso example code it got error message:

 ValueError: Layer sequential_1 expects 1 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 8) dtype=float32>, <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float32>]

can you concur on this ? or anything wrong with the installation? or a bug?
Thank you.
[talos_test.ipynb.zip](https://github.com/autonomio/talos/files/5569897/talos_test.ipynb.zip)

**Comment by paloma-ecg** [comment]
I've been checking your code, it looks like you have a mistake in lines #12 and #13 of your diabetes model. However, it is true that after running your code I've obtained the mistake you got. This mistake is due to an error in validation_data. You should change `validation_data = [x_val, y_val] `into `validaton_data = (x_val, y_val)`, and it works perfectly for me.

**Comment by zzhulm** [comment]
seems to be the problem, it is in model.fit() so it is not talos 's problem, it should be from the tensorflow update inconsistency issue,
right?
